ALTER TYPE "ProductCategory" ADD VALUE 'CARD_BINDER';
ALTER TYPE "ProductCategory" ADD VALUE 'TOP_LOADER';
ALTER TYPE "ProductCategory" ADD VALUE 'CARD_SLEEVES';
ALTER TYPE "ProductCategory" ADD VALUE 'PLAYMAT';
ALTER TYPE "ProductCategory" ADD VALUE 'DECK_BOX';
